# docker-compose.yml
version: '3.8'

services:
  alpine_service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - GITHUB_EMAIL=${GITHUB_EMAIL}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REPO_LOCAL_PATH=${REPO_LOCAL_PATH}
    container_name: alpine_container
    restart: always
    env_file:
      - .env
    volumes:
    - ${REPO_LOCAL_PATH}:/repo